%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    /Volumes/DQ-2013-2/Respirometry/BreathFreq/CommentFiles/Kolohe13_266_C_comment.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/01/28 09:08:41

%% Import the data
[~, ~, raw] = xlsread('/Volumes/DQ-2013-2/Respirometry/BreathFreq/CommentFiles/Nainoa13_276_C_comment.xlsx','Sheet1');
raw = raw(:,2:end);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,3);
raw = raw(:,[1,2]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
comm = data(:,1);
time = data(:,2);
cue = cellVectors(:,1);

%% Clear temporary variables
clearvars data raw cellVectors R;